---
#
# This playbook is for site-local customization to ElastiCluster's
# playbooks.  It runs *after* any other playbook distributed with
# ElastiCluster has gotten its chance to run.
#
# An empty playbook is checked into the Git repository.  If you make
# any local modifications, please run `git update-index
# --assume-unchanged after.yml` to avoid committing them accidentally
# into ElastiCluster's main branch.
#  

- name: Add user to cluster
  hosts: slurm_master slurm_worker 
  tasks:
    - name: Add the user 'user'
      user:
        name: user
        uid: 1040
        comment: John Doe
        shell: /bin/bash

# - name: Apply customizations to master Slurm node
#   hosts: slurm_master
#   roles:
#     - role: code 