---
#
#  Check if aiida is installed, if not, then install every package
#

- name: Aiida host playbook
  hosts: aiida_host
  roles: 
    - aiida

- name: Add user to cluster
  hosts: slurm_master slurm_worker 
  tasks:
    - name: Add the user 'user'
      user:
        name: user
        uid: 1040
        comment: John Doe
        shell: /bin/bash

- name: Add code customizations to the cluster
  hosts: slurm_master
  roles: 
    - code

