---
#
# Set variables for Debian/Ubuntu variants
#

- name: Set Aiida host variables (Debian/Ubuntu)
  tags:
    - aiida
  set_fact:
    aiida_packages:
      - gcc
      - postgresql
      - postgresql-client
      - postgresql-contrib
      - rabbitmq-server
      - python-psycopg2
      - python3-psycopg2
    postgresql_service_name: postgresql
    need_ssl: ssl|default("false")|bool
    ip: '{{ansible_default_ipv4.address}}'
  when: is_debian_compatible
