---

- name: Install packages needed for AiiDA restapi
  package:
    name: 
     - nginx
     - supervisor
     - python-passlib
     - python-openssl
    state: '{{ pkg_install_state }}'

- name: Install python passlib needed for AiiDA restapi
  pip:
    executable: pip3
    name: 
      - passlib

- name: Install config files for RestAPI services (supervisor)
  copy:
    src: 'etc/supervisor/supervisord.conf' 
    dest: '/etc/supervisor/supervisord.conf'
    mode: '0644'

- name: Install config files for RestAPI services (nginx)
  template:
    src: 'etc/nginx/nginx.conf.j2' 
    dest: '/etc/nginx/nginx.conf'
    mode: '0644'

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: /etc/nginx/localhost.key
  when: 'need_ssl'

- name: Generate a certificate signing request
  openssl_csr:
    path: /etc/nginx/localhost.csr
    privatekey_path: /etc/nginx/localhost.key
    common_name: '{{ip}}'
    subject_alt_name: 'IP:{{ip}}'
    key_usage:
     - digitalSignature
    extended_key_usage:
     - serverAuth
  when: 'need_ssl'

- name: Generate a self-signed certificate
  openssl_certificate:
    path: /etc/nginx/localhost.crt
    privatekey_path: /etc/nginx/localhost.key
    csr_path: /etc/nginx/localhost.csr
    provider: selfsigned
  when: 'need_ssl'

- name: Install nginx .htpasswd file
  htpasswd:
    path: '/etc/nginx/.htpasswd'
    name: "{{hostvars[groups['aiida_host'][0]]['api_user']}}"
    password: "{{hostvars[groups['aiida_host'][0]]['api_pass']}}"
    owner: root
    group: www-data
    mode: 0640

- name: Ensure RestAPI services are started
  service:
    name: '{{item}}'
    enabled: yes
    state: started
  loop:
    - 'supervisor'
    - 'nginx' 

- name: Open port for RestAPI
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 18080
    jump: ACCEPT

# - name: Start AiiDA RestAPI
#   command: |
#     verdi restapi
